# Generated by Django 5.2.5 on 2025-08-23 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('ESSAY', 'Essay'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('SINGLE_CHOICE', 'Single Choice')], default='ESSAY', max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='applications.job')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_answers', to='applications.applicant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.question')),
            ],
        ),
    ]
