# Generated by Django 5.2.5 on 2025-08-23 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_question_assessmentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='custom_questions',
            field=models.ManyToManyField(blank=True, related_name='custom_jobs', to='applications.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_template_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('ESSAY', 'Essay'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('SINGLE_CHOICE', 'Single Choice'), ('FILE_UPLOAD', 'File Upload'), ('CODING_CHALLENGE', 'Coding Challenge'), ('TEXT_INPUT', 'Text Input'), ('INTEGER_INPUT', 'Integer Input')], default='ESSAY', max_length=50),
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('questions', models.ManyToManyField(related_name='templates', to='applications.question')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='assessment_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.assessmenttemplate'),
        ),
    ]
